regiao(região-norte).
regiao(região-nordeste).
regiao(região-sudeste).
regiao(região-sul).
regiao(região-centro-oeste).

estado(ro).
estado(ac).
estado(am).
estado(rr).
estado(pa).
estado(ap).
estado(to).
estado(ma).
estado(pi).
estado(ce).
estado(rn).
estado(pb).
estado(pe).
estado(al).
estado(se).
estado(ba).
estado(mg).
estado(es).
estado(rj).
estado(sp).
estado(pr).
estado(sc).
estado(rs).
estado(ms).
estado(mt).
estado(go).
estado(df).

estado_de(ro,região-norte).
estado_de(ac,região-norte).
estado_de(am,região-norte).
estado_de(rr,região-norte).
estado_de(pa,região-norte).
estado_de(ap,região-norte).
estado_de(to,região-norte).
estado_de(ma,região-nordeste).
estado_de(pi,região-nordeste).
estado_de(ce,região-nordeste).
estado_de(rn,região-nordeste).
estado_de(pb,região-nordeste).
estado_de(pe,região-nordeste).
estado_de(al,região-nordeste).
estado_de(se,região-nordeste).
estado_de(ba,região-nordeste).
estado_de(mg,região-sudeste).
estado_de(es,região-sudeste).
estado_de(rj,região-sudeste).
estado_de(sp,região-sudeste).
estado_de(pr,região-sul).
estado_de(sc,região-sul).
estado_de(rs,região-sul).
estado_de(ms,região-centro-oeste).
estado_de(mt,região-centro-oeste).
estado_de(go,região-centro-oeste).
estado_de(df,região-centro-oeste).

capital(porto-velho).
capital(rio-branco).
capital(manaus).
capital(boa-vista).
capital(belém).
capital(macapá).
capital(palmas).
capital(são-luís).
capital(teresina).
capital(fortaleza).
capital(natal).
capital(joão-pessoa).
capital(recife).
capital(maceió).
capital(aracaju).
capital(salvador).
capital(belo-horizonte).
capital(vitória).
capital(rio-de-janeiro).
capital(são-paulo).
capital(curitiba).
capital(florianópolis).
capital(porto-alegre).
capital(campo-grande).
capital(cuiabá).
capital(goiânia).
capital(brasília).

capital_de(porto-velho,ro).
capital_de(rio-branco,ac).
capital_de(manaus,am).
capital_de(boa-vista,rr).
capital_de(belém,pa).
capital_de(macapá,ap).
capital_de(palmas,to).
capital_de(são-luís,ma).
capital_de(teresina,pi).
capital_de(fortaleza,ce).
capital_de(natal,rn).
capital_de(joão-pessoa,pb).
capital_de(recife,pe).
capital_de(maceió,al).
capital_de(aracaju,se).
capital_de(salvador,ba).
capital_de(belo-horizonte,mg).
capital_de(vitória,es).
capital_de(rio-de-janeiro,rj).
capital_de(são-paulo,sp).
capital_de(curitiba,pr).
capital_de(florianópolis,sc).
capital_de(porto-alegre,rs).
capital_de(campo-grande,ms).
capital_de(cuiabá,mt).
capital_de(goiânia,go).
capital_de(brasília,df).

tamanho_de(porto-velho,pequeno).
tamanho_de(rio-branco,pequeno).
tamanho_de(manaus,grande).
tamanho_de(boa-vista,pequeno).
tamanho_de(belém,grande).
tamanho_de(macapá,pequeno).
tamanho_de(palmas,pequeno).
tamanho_de(são-luís,grande).
tamanho_de(teresina,pequeno).
tamanho_de(fortaleza,grande).
tamanho_de(natal,pequeno).
tamanho_de(joão-pessoa,pequeno).
tamanho_de(recife,grande).
tamanho_de(maceió,grande).
tamanho_de(aracaju,pequeno).
tamanho_de(salvador,grande).
tamanho_de(belo-horizonte,grande).
tamanho_de(vitória,pequeno).
tamanho_de(rio-de-janeiro,grande).
tamanho_de(são-paulo,grande).
tamanho_de(curitiba,grande).
tamanho_de(florianópolis,pequeno).
tamanho_de(porto-alegre,grande).
tamanho_de(campo-grande,pequeno).
tamanho_de(cuiabá,pequeno).
tamanho_de(goiânia,grande).
tamanho_de(brasília,grande).

